### ISSUE TITLE
Statusline shows error

### ISSUE THREAD

**Issue by ghost** [SpaceVim/SpaceVim#2312]
## Expected behavior, english is required
Statusline shows error
I have installed nerd-fonts
But still can't display anything other than nil

## The reproduce ways from Vim starting (Required!)
Every time I open neovim

## Debug info
SpaceVim layers:

- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete
- chat:                 not loaded          https://spacevim.org/layers/chat
+ checkers:                 loaded          https://spacevim.org/layers/checkers
- chinese:              not loaded          https://spacevim.org/layers/chinese
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme
+ core/banner:              loaded          https://spacevim.org/layers/core/banner
+ core/statusline:          loaded          https://spacevim.org/layers/core/statusline
+ core/tabline:             loaded          https://spacevim.org/layers/core/tabline
+ core:                     loaded          https://spacevim.org/layers/core
- cscope:               not loaded          https://spacevim.org/layers/cscope
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp
- debug:                not loaded          https://spacevim.org/layers/debug
- denite:               not loaded          https://spacevim.org/layers/denite
+ edit:                     loaded          https://spacevim.org/layers/edit
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits
+ format:                   loaded          https://spacevim.org/layers/format
- fzf:                  not loaded          https://spacevim.org/layers/fzf
- games:                not loaded          no exists
- git:                  not loaded          https://spacevim.org/layers/git
- github:               not loaded          https://spacevim.org/layers/github
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese
- lang/WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly
- lang/agda:            not loaded          https://spacevim.org/layers/lang/agda
- lang/asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc
- lang/autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey
+ lang/c:                   loaded          https://spacevim.org/layers/lang/c
- lang/clojure:         not loaded          https://spacevim.org/layers/lang/clojure
- lang/crystal:         not loaded          no exists
- lang/csharp:          not loaded          https://spacevim.org/layers/lang/csharp
- lang/dart:            not loaded          https://spacevim.org/layers/lang/dart
- lang/dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile
- lang/elixir:          not loaded          https://spacevim.org/layers/lang/elixir
- lang/elm:             not loaded          https://spacevim.org/layers/lang/elm
- lang/erlang:          not loaded          https://spacevim.org/layers/lang/erlang
- lang/extra:           not loaded          https://spacevim.org/layers/lang/extra
- lang/fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp
- lang/go:              not loaded          https://spacevim.org/layers/lang/go
- lang/graphql:         not loaded          https://spacevim.org/layers/lang/graphql
- lang/haskell:         not loaded          https://spacevim.org/layers/lang/haskell
- lang/html:            not loaded          https://spacevim.org/layers/lang/html
- lang/java:            not loaded          https://spacevim.org/layers/lang/java
- lang/javascript:      not loaded          https://spacevim.org/layers/lang/javascript
- lang/json:            not loaded          no exists
- lang/julia:           not loaded          https://spacevim.org/layers/lang/julia
- lang/kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin
- lang/latex:           not loaded          https://spacevim.org/layers/lang/latex
- lang/lisp:            not loaded          https://spacevim.org/layers/lang/lisp
- lang/lua:             not loaded          https://spacevim.org/layers/lang/lua
- lang/markdown:        not loaded          https://spacevim.org/layers/lang/markdown
- lang/nim:             not loaded          https://spacevim.org/layers/lang/nim
- lang/ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml
- lang/perl:            not loaded          https://spacevim.org/layers/lang/perl
- lang/php:             not loaded          https://spacevim.org/layers/lang/php
- lang/plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml
- lang/pony:            not loaded          no exists
- lang/ps1:             not loaded          no exists
- lang/puppet:          not loaded          https://spacevim.org/layers/lang/puppet
- lang/purescript:      not loaded          https://spacevim.org/layers/lang/purescript
- lang/python:          not loaded          https://spacevim.org/layers/lang/python
- lang/r:               not loaded          no exists
- lang/ruby:            not loaded          https://spacevim.org/layers/lang/ruby
- lang/rust:            not loaded          https://spacevim.org/layers/lang/rust
- lang/scala:           not loaded          https://spacevim.org/layers/lang/scala
- lang/scheme:          not loaded          https://spacevim.org/layers/lang/scheme
- lang/sh:              not loaded          https://spacevim.org/layers/lang/sh
- lang/solidity:        not loaded          no exists
- lang/swift:           not loaded          https://spacevim.org/layers/lang/swift
- lang/swig:            not loaded          no exists
- lang/toml:            not loaded          no exists
- lang/typescript:      not loaded          https://spacevim.org/layers/lang/typescript
- lang/vim:             not loaded          https://spacevim.org/layers/lang/vim
- lang/vue:             not loaded          https://spacevim.org/layers/lang/vue
- lang/xml:             not loaded          no exists
- leaderf:              not loaded          https://spacevim.org/layers/leaderf
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell
- sudo:                 not loaded          https://spacevim.org/layers/sudo
- tags:                 not loaded          https://spacevim.org/layers/tags
- tmux:                 not loaded          https://spacevim.org/layers/tmux
- tools/dash:           not loaded          https://spacevim.org/layers/tools/dash
- tools/screensaver:    not loaded          no exists
- tools:                not loaded          https://spacevim.org/layers/tools
+ ui:                       loaded          https://spacevim.org/layers/ui
- unite:                not loaded          https://spacevim.org/layers/unite
- vim:                  not loaded          no exists

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.1
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'one'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['rakr/vim-one', {'name': 'rakr/vim-one', 'merged': 0}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/rivennero/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'chromatica.nvim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'curve'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'curve'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
  clang_executable='/usr/bin/clang'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:06:38] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [09:06:38] [ Info ] find local conf: /home/rivennero/.SpaceVim.d/init.toml
[ SpaceVim ] [09:06:38] [ Info ] loadding cached local conf: /home/rivennero/.cache/SpaceVim/conf/_home_rivennero__SpaceVim_d_init_toml.json
[ SpaceVim ] [09:06:38] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [09:06:38] [ Info ] Start to find root for: 
[ SpaceVim ] [09:06:38] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [09:06:38] [ Info ] Start to find root for: 
[ SpaceVim ] [09:06:40] [ Info ] Start to find root for: /tmp/nvimTIZqLn/1/issue_report.md
```
</details>

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.1
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'one'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['rakr/vim-one', {'name': 'rakr/vim-one', 'merged': 0}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/rivennero/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'chromatica.nvim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'curve'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'curve'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
  clang_executable='/usr/bin/clang'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:06:38] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [09:06:38] [ Info ] find local conf: /home/rivennero/.SpaceVim.d/init.toml
[ SpaceVim ] [09:06:38] [ Info ] loadding cached local conf: /home/rivennero/.cache/SpaceVim/conf/_home_rivennero__SpaceVim_d_init_toml.json
[ SpaceVim ] [09:06:38] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [09:06:38] [ Info ] Start to find root for: 
[ SpaceVim ] [09:06:38] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [09:06:38] [ Info ] Start to find root for: 
[ SpaceVim ] [09:06:40] [ Info ] Start to find root for: /tmp/nvimTIZqLn/1/issue_report.md
```

## Screenshots
![image](https://user-images.githubusercontent.com/35187885/49215501-e5115e00-f403-11e8-80bf-4280c56b94f9.png)
![image](https://user-images.githubusercontent.com/35187885/49215563-07a37700-f404-11e8-8385-1c6a11055f9e.png)
